//
// Generated file, do not edit! Created by opp_msgtool 6.2 from MstClusteringPacket.msg.
//

#ifndef __MSTCLUSTERING_MSTCLUSTERINGPACKET_M_H
#define __MSTCLUSTERING_MSTCLUSTERINGPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace mstclustering {

class HelloPacket;
class TopologyUpdatePacket;
class ClusterJoinPacket;
class ClusterHeadPacket;
class EdgeInfoPacket;

}  // namespace mstclustering

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace mstclustering {

/**
 * Enum generated from <tt>MstClusteringPacket.msg:6</tt> by opp_msgtool.
 * <pre>
 * enum MstClusteringMsgType
 * {
 *     MSG_HELLO = 0;
 *     MSG_TOPOLOGY_UPDATE = 1;
 *     MSG_CLUSTER_JOIN = 2;
 *     MSG_CLUSTER_HEAD = 3;
 *     MSG_CLUSTER_ACK = 4;
 *     MSG_CLUSTER_LEAVE = 5;
 *     MSG_EDGE_INFO = 6;
 * }
 * </pre>
 */
enum MstClusteringMsgType {
    MSG_HELLO = 0,
    MSG_TOPOLOGY_UPDATE = 1,
    MSG_CLUSTER_JOIN = 2,
    MSG_CLUSTER_HEAD = 3,
    MSG_CLUSTER_ACK = 4,
    MSG_CLUSTER_LEAVE = 5,
    MSG_EDGE_INFO = 6
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MstClusteringMsgType& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MstClusteringMsgType& e) { int n; b->unpack(n); e = static_cast<MstClusteringMsgType>(n); }

/**
 * Enum generated from <tt>MstClusteringPacket.msg:16</tt> by opp_msgtool.
 * <pre>
 * enum NodeRole
 * {
 *     ROLE_UNDECIDED = 0;
 *     ROLE_CLUSTER_MEMBER = 1;
 *     ROLE_CLUSTER_HEAD = 2;
 *     ROLE_GATEWAY = 3;
 * }
 * </pre>
 */
enum NodeRole {
    ROLE_UNDECIDED = 0,
    ROLE_CLUSTER_MEMBER = 1,
    ROLE_CLUSTER_HEAD = 2,
    ROLE_GATEWAY = 3
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const NodeRole& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, NodeRole& e) { int n; b->unpack(n); e = static_cast<NodeRole>(n); }

/**
 * Class generated from <tt>MstClusteringPacket.msg:23</tt> by opp_msgtool.
 * <pre>
 * class HelloPacket extends inet::FieldsChunk
 * {
 *     int nodeId;
 *     double posX;
 *     double posY;
 *     double posZ;
 *     double energy;
 *     int clusterId = -1;
 *     int clusterHeadId = -1;
 *     int nodeRole;
 *     int sequenceNumber;
 *     int numNeighbors;
 *     simtime_t timestamp;
 * }
 * </pre>
 */
class HelloPacket : public ::inet::FieldsChunk
{
  protected:
    int nodeId = 0;
    double posX = 0;
    double posY = 0;
    double posZ = 0;
    double energy = 0;
    int clusterId = -1;
    int clusterHeadId = -1;
    int nodeRole = 0;
    int sequenceNumber = 0;
    int numNeighbors = 0;
    ::omnetpp::simtime_t timestamp = SIMTIME_ZERO;

  private:
    void copy(const HelloPacket& other);

  protected:
    bool operator==(const HelloPacket&) = delete;

  public:
    HelloPacket();
    HelloPacket(const HelloPacket& other);
    virtual ~HelloPacket();
    HelloPacket& operator=(const HelloPacket& other);
    virtual HelloPacket *dup() const override {return new HelloPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getNodeId() const;
    virtual void setNodeId(int nodeId);

    virtual double getPosX() const;
    virtual void setPosX(double posX);

    virtual double getPosY() const;
    virtual void setPosY(double posY);

    virtual double getPosZ() const;
    virtual void setPosZ(double posZ);

    virtual double getEnergy() const;
    virtual void setEnergy(double energy);

    virtual int getClusterId() const;
    virtual void setClusterId(int clusterId);

    virtual int getClusterHeadId() const;
    virtual void setClusterHeadId(int clusterHeadId);

    virtual int getNodeRole() const;
    virtual void setNodeRole(int nodeRole);

    virtual int getSequenceNumber() const;
    virtual void setSequenceNumber(int sequenceNumber);

    virtual int getNumNeighbors() const;
    virtual void setNumNeighbors(int numNeighbors);

    virtual ::omnetpp::simtime_t getTimestamp() const;
    virtual void setTimestamp(::omnetpp::simtime_t timestamp);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const HelloPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, HelloPacket& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>MstClusteringPacket.msg:37</tt> by opp_msgtool.
 * <pre>
 * class TopologyUpdatePacket extends inet::FieldsChunk
 * {
 *     int sourceId;
 *     int destId;
 *     double weight;
 *     bool isActive;
 *     int sequenceNumber;
 * }
 * </pre>
 */
class TopologyUpdatePacket : public ::inet::FieldsChunk
{
  protected:
    int sourceId = 0;
    int destId = 0;
    double weight = 0;
    bool isActive_ = false;
    int sequenceNumber = 0;

  private:
    void copy(const TopologyUpdatePacket& other);

  protected:
    bool operator==(const TopologyUpdatePacket&) = delete;

  public:
    TopologyUpdatePacket();
    TopologyUpdatePacket(const TopologyUpdatePacket& other);
    virtual ~TopologyUpdatePacket();
    TopologyUpdatePacket& operator=(const TopologyUpdatePacket& other);
    virtual TopologyUpdatePacket *dup() const override {return new TopologyUpdatePacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSourceId() const;
    virtual void setSourceId(int sourceId);

    virtual int getDestId() const;
    virtual void setDestId(int destId);

    virtual double getWeight() const;
    virtual void setWeight(double weight);

    virtual bool isActive() const;
    virtual void setIsActive(bool isActive);

    virtual int getSequenceNumber() const;
    virtual void setSequenceNumber(int sequenceNumber);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TopologyUpdatePacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TopologyUpdatePacket& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>MstClusteringPacket.msg:45</tt> by opp_msgtool.
 * <pre>
 * class ClusterJoinPacket extends inet::FieldsChunk
 * {
 *     int nodeId;
 *     int clusterId;
 *     int clusterHeadId;
 *     double energy;
 *     int sequenceNumber;
 * }
 * </pre>
 */
class ClusterJoinPacket : public ::inet::FieldsChunk
{
  protected:
    int nodeId = 0;
    int clusterId = 0;
    int clusterHeadId = 0;
    double energy = 0;
    int sequenceNumber = 0;

  private:
    void copy(const ClusterJoinPacket& other);

  protected:
    bool operator==(const ClusterJoinPacket&) = delete;

  public:
    ClusterJoinPacket();
    ClusterJoinPacket(const ClusterJoinPacket& other);
    virtual ~ClusterJoinPacket();
    ClusterJoinPacket& operator=(const ClusterJoinPacket& other);
    virtual ClusterJoinPacket *dup() const override {return new ClusterJoinPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getNodeId() const;
    virtual void setNodeId(int nodeId);

    virtual int getClusterId() const;
    virtual void setClusterId(int clusterId);

    virtual int getClusterHeadId() const;
    virtual void setClusterHeadId(int clusterHeadId);

    virtual double getEnergy() const;
    virtual void setEnergy(double energy);

    virtual int getSequenceNumber() const;
    virtual void setSequenceNumber(int sequenceNumber);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ClusterJoinPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ClusterJoinPacket& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>MstClusteringPacket.msg:53</tt> by opp_msgtool.
 * <pre>
 * class ClusterHeadPacket extends inet::FieldsChunk
 * {
 *     int clusterId;
 *     int clusterHeadId;
 *     int memberCount;
 *     double avgEnergy;
 *     int sequenceNumber;
 * }
 * </pre>
 */
class ClusterHeadPacket : public ::inet::FieldsChunk
{
  protected:
    int clusterId = 0;
    int clusterHeadId = 0;
    int memberCount = 0;
    double avgEnergy = 0;
    int sequenceNumber = 0;

  private:
    void copy(const ClusterHeadPacket& other);

  protected:
    bool operator==(const ClusterHeadPacket&) = delete;

  public:
    ClusterHeadPacket();
    ClusterHeadPacket(const ClusterHeadPacket& other);
    virtual ~ClusterHeadPacket();
    ClusterHeadPacket& operator=(const ClusterHeadPacket& other);
    virtual ClusterHeadPacket *dup() const override {return new ClusterHeadPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getClusterId() const;
    virtual void setClusterId(int clusterId);

    virtual int getClusterHeadId() const;
    virtual void setClusterHeadId(int clusterHeadId);

    virtual int getMemberCount() const;
    virtual void setMemberCount(int memberCount);

    virtual double getAvgEnergy() const;
    virtual void setAvgEnergy(double avgEnergy);

    virtual int getSequenceNumber() const;
    virtual void setSequenceNumber(int sequenceNumber);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ClusterHeadPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ClusterHeadPacket& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>MstClusteringPacket.msg:61</tt> by opp_msgtool.
 * <pre>
 * class EdgeInfoPacket extends inet::FieldsChunk
 * {
 *     int sourceId;
 *     int destId;
 *     double weight;
 *     int mstId;
 *     int sequenceNumber;
 * }
 * </pre>
 */
class EdgeInfoPacket : public ::inet::FieldsChunk
{
  protected:
    int sourceId = 0;
    int destId = 0;
    double weight = 0;
    int mstId = 0;
    int sequenceNumber = 0;

  private:
    void copy(const EdgeInfoPacket& other);

  protected:
    bool operator==(const EdgeInfoPacket&) = delete;

  public:
    EdgeInfoPacket();
    EdgeInfoPacket(const EdgeInfoPacket& other);
    virtual ~EdgeInfoPacket();
    EdgeInfoPacket& operator=(const EdgeInfoPacket& other);
    virtual EdgeInfoPacket *dup() const override {return new EdgeInfoPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSourceId() const;
    virtual void setSourceId(int sourceId);

    virtual int getDestId() const;
    virtual void setDestId(int destId);

    virtual double getWeight() const;
    virtual void setWeight(double weight);

    virtual int getMstId() const;
    virtual void setMstId(int mstId);

    virtual int getSequenceNumber() const;
    virtual void setSequenceNumber(int sequenceNumber);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const EdgeInfoPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, EdgeInfoPacket& obj) {obj.parsimUnpack(b);}


}  // namespace mstclustering


namespace omnetpp {

template<> inline mstclustering::HelloPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<mstclustering::HelloPacket*>(ptr.get<cObject>()); }
template<> inline mstclustering::TopologyUpdatePacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<mstclustering::TopologyUpdatePacket*>(ptr.get<cObject>()); }
template<> inline mstclustering::ClusterJoinPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<mstclustering::ClusterJoinPacket*>(ptr.get<cObject>()); }
template<> inline mstclustering::ClusterHeadPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<mstclustering::ClusterHeadPacket*>(ptr.get<cObject>()); }
template<> inline mstclustering::EdgeInfoPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<mstclustering::EdgeInfoPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __MSTCLUSTERING_MSTCLUSTERINGPACKET_M_H

